#include "DBI-ILI9806.h"

static DBIPacketStruct ILI9806Configs[] = {
    // EXTC Command Set enable register
    MakeDBIPacket(0xFF, 0xFF, 0x98, 0x06),

    // GIP 1
    MakeDBIPacket(0xBC, 0x01, 0x0F, 0x61, 0xFF, 0x01, 0x01, 0x0B, 0x10, 0x37, 0x63, 0xFF, 0xFF, 0x01, 0x01, 0x00, 0x00, 0xFF, 0x52, 0x01, 0x00, 0x40),

    // GIP 2
    MakeDBIPacket(0xBD, 0x01, 0x23, 0x45, 0x67, 0x01, 0x23, 0x45, 0x67),

    // GIP 3
    MakeDBIPacket(0xBE, 0x00, 0x01, 0xAB, 0x60, 0x22, 0x22, 0x22, 0x22, 0x22),

    // VCOM Control
    MakeDBIPacket(0xC7, 0x36),

    // EN_volt_reg VGMP / VGMN /VGSP / VGSN voltage to output
    MakeDBIPacket(0xED, 0x7F, 0x0F),

    // Power Control 1	Setting AVDD / AVEE / VGH / VGL
    // VGH 15V,VGLO-10V
    MakeDBIPacket(0XC0, 0x0F, 0x0B, 0x0A),

    // AVDD / AVEE generated by internal pumping.
    MakeDBIPacket(0XFC, 0x08),

    MakeDBIPacket(0XDF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20),

    // DVDD Voltage Setting
    MakeDBIPacket(0XF3, 0x74),

    // Inversion Type
    MakeDBIPacket(0xB4, 0x00, 0x00, 0x00),

    // Resolution Control
    MakeDBIPacket(0xF7, 0x82), //480*800

    // FRAME RATE Setting
    MakeDBIPacket(0xB1, 0x00, 0x13, 0x13),

    // CR_EQ_PC_SDT  #C0,06,40,28
    MakeDBIPacket(0XF2, 0x80, 0x04, 0x40, 0x28),

    // Power Control 2	 SD OP Bias_VRH1_VRH2_EXT_CPCK_SEL
    MakeDBIPacket(0XC1, 0x17, 0x88, 0x88, 0x20),

    //Positive Gamma Control
    MakeDBIPacket(0xE0, 0x00, 0x0A, 0x12, 0x10, 0x0E, 0x20, 0xCC, 0x07, 0x06, 0x0B, 0x0E, 0x0F, 0x0D, 0x15, 0x10, 0x00),

    // Negative Gamma Correction
    MakeDBIPacket(0xE1, 0x00, 0x0B, 0x13, 0x0D, 0x0E, 0x1B, 0x71, 0x06, 0x06, 0x0A, 0x0F, 0x0E, 0x0F, 0x15, 0x0C, 0x00),

    MakeDBIPacket(0x2a, 0x00, 0x00, 0x01, 0xdf),

    MakeDBIPacket(0x2b, 0x00, 0x00, 0x03, 0x1f),

    // Pixel Format
    MakeDBIPacket(0x3A, 0x55),

    // Memory Access Control
    MakeDBIPacket(0x36, 3 << 5), //02-180

    MakeDBIPacket(0x11),

    MakeDBIDelay(120),

    MakeDBIPacket(0x29),

    MakeDBIDelay(20),

    MakeDBIPacket(0x2C),

    MakeDBIPacketEnd(),
};

static DBIPacketStruct ReadSequence[] = {
    MakeDBIPacketRead(0xD3, 1, 3),

    MakeDBIPacketEnd(),
};

#define ILI9806_DISPLAY_ID 0x00980600

bool ILI9806Constractor(DisplayStruct* display) {
    DisplayStartupSequence(display, true, true, 20, 20, 120);

    display->SetupTime = 30;
    display->BusWidth  = 16;
    if (DisplayDBIReadID(display, ReadSequence) != ILI9806_DISPLAY_ID)
        return false;

    display->ID = ILI9806_DISPLAY_ID;

    display->HorizontalActive = 800;
    display->VerticalActive   = 480;

    display->RefreshMode = DisplayRefreshAdaptive;

    display->DBIConfigPackets = ILI9806Configs;

    return true;
}
